version: "3.8"

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 3000:${PORT_DEV}
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql
  
  mysql:
    image: mysql:8.0
    restart: always
    environment: 
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

    